openapi: 3.0.0
info:
  title: LED Name Badge API
  description: API for controlling the LED name badge
  version: 1.0.0
paths:
  /display-text:
    post:
      summary: Display text on the LED name badge
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: "Hello, World!"
      responses:
        '200':
          description: Text displayed on LED
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Text displayed on LED"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request"
